# Generated by Django 4.0 on 2022-02-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_course'),
        ('authentication', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Año Escolar'),
        ),
    ]
