# Generated by Django 4.0 on 2022-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_course_options'),
        ('authentication', '0006_alter_student_school_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_year__order'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.ManyToManyField(to='school.SchoolYear', verbose_name='Año Escolar'),
        ),
    ]
