# Generated by Django 4.0 on 2022-02-06 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_course_options'),
        ('authentication', '0007_alter_student_options_remove_student_school_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Año Escolar'),
        ),
    ]
