# Generated by Django 4.0 on 2022-02-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
