# Generated by Django 4.0 on 2022-02-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schoolyear_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': 'Año Escolar', 'verbose_name_plural': 'Años Escolares'},
        ),
    ]
