# Generated by Django 4.0 on 2022-02-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_student_user'),
        ('school', '0004_schoolyear_head_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='head_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher', verbose_name='Profesor jefe'),
        ),
    ]
