# Generated by Django 4.0 on 2022-02-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_student_school_year'),
        ('school', '0007_alter_course_options_alter_schoolyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['order'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student', verbose_name='Estudiantes'),
        ),
    ]
