# Generated by Django 4.0 on 2022-02-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_student_school_year'),
        ('school', '0008_alter_schoolyear_options_schoolyear_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='head_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher', verbose_name='Profesor jefe'),
        ),
    ]
