# Generated by Django 4.0 on 2022-02-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_schoolyear_head_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear', verbose_name='Curso'),
        ),
    ]
