# Generated by Django 4.0 on 2022-02-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_student_school_year'),
        ('school', '0010_course_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students_who_join',
            field=models.ManyToManyField(related_name='students_who_join', to='authentication.Student', verbose_name='Estudiantes'),
        ),
    ]
